# main.yml

- name: CONDA | get conda-recipes from git repository
  git: repo={{ conda_recipes_url }} dest={{ conda_dest }} accept_hostkey=yes
  register: conda_recipes_downloaded

- name: CONDA | get extra conda-recipes from git repository
  git: repo={{ extra_conda_recipes_url }} dest={{ extra_conda_dest }} accept_hostkey=yes
  register: conda_recipes_downloaded

- name: CONDA | merge extra conda-recipes into main conda-recipes
  shell: ls -d {{ extra_conda_dest }}/
  register: dir_names

- name: CONDA | merge extra conda-recipes into main conda-recipes
  command: mv {{ item }} {{ conda_dest }}/
  with_items: dir_names.stdout_lines

- name: CONDA | install conda-build
  conda: name=conda-build executable={{ conda_dir }}/bin/conda

- name: CONDA | install ipython
  conda: name=ipython executable={{ conda_dir }}/bin/conda

- name: CONDA | build and install packages
  conda: name={{ item }}
         executable={{ conda_dir }}/bin/conda
         source={{ conda_dest }}/python/{{ item }}
         extra_args="--use-local"
  with_items: conda_packages
  register: output
