# main.yml

- name: CONDA | get conda-recipes from git repository
  git: repo={{ conda_recipes_url }} dest={{ conda_dest}} accept_hostkey=yes
  register: conda_recipes_downloaded

- name: CONDA | install conda-build
  conda: name=conda-build executable={{ conda_dir }}/bin/conda

- name: CONDA | install ipython
  conda: name=ipython executable={{ conda_dir }}/bin/conda

- name: CONDA | install jedi
  conda: name=jedi executable={{ conda_dir }}/bin/conda source="{{ conda_dest}}/python/jedi" extra_args="--use-local"


- name: CONDA | install sexpdata
  conda: name=sexpdata executable={{ conda_dir }}/bin/conda source="{{ conda_dest}}/python/sexpdata" extra_args="--use-local"

- name: CONDA | install epc
  conda: name=epc executable={{ conda_dir }}/bin/conda source="{{ conda_dest}}/python/epc" extra_args="--use-local"

# - name: CONDA | install Anaconda
#   conda: name=anaconda executable={{ conda_dir }}/bin/conda

#   # how to make jedi to work with emacs and anaconda
#   # http://stackoverflow.com/questions/21703693/can-virtualenv-be-avoided-when-using-emacs-jedi-in-anaconda
# - name: CONDA | install Jedi
#   conda: name=jedi executable={{ conda_dir }}/bin/conda state=latest

# - name: CONDA | install sexpdata
#   #conda install -c https://conda.anaconda.org/nsidc sexpdata
#   conda: name=sexpdata executable={{ conda_dir }}/bin/conda state=latest channels="https://conda.anaconda.org/auto"

# - name: CONDA | install EPC
#   #conda install -c https://conda.anaconda.org/nsidc epc
#   conda: name=epc executable={{ conda_dir }}/bin/conda state=latest channels="https://conda.anaconda.org/auto"
